CREATE TABLE users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  openid VARCHAR(128) NOT NULL UNIQUE,
  unionid VARCHAR(128) NULL,
  nickname VARCHAR(64) NOT NULL,
  avatar VARCHAR(512) NULL,
  birthday DATE NULL,
  gender VARCHAR(20) NULL,
  role VARCHAR(20) NOT NULL,
  phone VARCHAR(32) NULL,
  preferred_name VARCHAR(64) NULL,
  comfort_preference VARCHAR(255) NULL,
  dislike_expression VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE couples (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  partner_id BIGINT NULL,
  love_start_date DATE NULL,
  bind_code VARCHAR(32) NOT NULL UNIQUE,
  bind_code_expired_at DATETIME NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE user_privacy_settings (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL UNIQUE,
  allow_wish_view BOOLEAN NOT NULL DEFAULT TRUE,
  allow_emotion_notify BOOLEAN NOT NULL DEFAULT TRUE,
  allow_period_notify BOOLEAN NOT NULL DEFAULT FALSE,
  allow_mood_view BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE important_dates (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  couple_id BIGINT NULL,
  title VARCHAR(128) NOT NULL,
  date DATE NOT NULL,
  repeat_type VARCHAR(20) NOT NULL DEFAULT 'none',
  remind_days_before INT NOT NULL DEFAULT 0,
  show_on_home BOOLEAN NOT NULL DEFAULT TRUE,
  remind_partner BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE diaries (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  content TEXT NOT NULL,
  mood_score INT NOT NULL,
  ai_comfort_text TEXT NULL,
  emotion_level INT NULL,
  emotion_type VARCHAR(64) NULL,
  notify_partner BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE weather_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  city VARCHAR(64) NOT NULL,
  temperature_min INT NULL,
  temperature_max INT NULL,
  weather VARCHAR(64) NULL,
  rain_probability INT NULL,
  clothing_advice VARCHAR(255) NULL,
  skincare_advice VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE period_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NULL,
  pain_level VARCHAR(20) NULL,
  flow_level VARCHAR(20) NULL,
  mood VARCHAR(20) NULL,
  note TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE todos (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  due_date DATETIME NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'normal',
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  repeat_type VARCHAR(20) NOT NULL DEFAULT 'none',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE wishes (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  description TEXT NULL,
  image_url VARCHAR(512) NULL,
  category VARCHAR(64) NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'normal',
  progress INT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'wanted',
  claimed_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE wardrobe_items (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  image_url VARCHAR(512) NOT NULL,
  type VARCHAR(64) NULL,
  color VARCHAR(64) NULL,
  style VARCHAR(64) NULL,
  season VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE notifications (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  target_user_id BIGINT NOT NULL,
  type VARCHAR(64) NOT NULL,
  content TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
